# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cuelloGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cuello_label = QtWidgets.QLabel(self.centralwidget)
        self.cuello_label.setGeometry(QtCore.QRect(310, 60, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.cuello_label.setFont(font)
        self.cuello_label.setMouseTracking(False)
        self.cuello_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cuello_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cuello_label.setObjectName("cuello_label")
        self.cuelloHorizontalLabel = QtWidgets.QLabel(self.centralwidget)
        self.cuelloHorizontalLabel.setGeometry(QtCore.QRect(200, 270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cuelloHorizontalLabel.setFont(font)
        self.cuelloHorizontalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cuelloHorizontalLabel.setObjectName("cuelloHorizontalLabel")
        self.cuelloHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.cuelloHorizontalSlider.setGeometry(QtCore.QRect(50, 240, 351, 22))
        self.cuelloHorizontalSlider.setMaximum(180)
        self.cuelloHorizontalSlider.setSliderPosition(90)
        self.cuelloHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cuelloHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.cuelloHorizontalSlider.setTickInterval(0)
        self.cuelloHorizontalSlider.setObjectName("cuelloHorizontalSlider")
        self.cuelloVerticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.cuelloVerticalSlider.setGeometry(QtCore.QRect(530, 170, 22, 341))
        self.cuelloVerticalSlider.setMaximum(90)
        self.cuelloVerticalSlider.setPageStep(10)
        self.cuelloVerticalSlider.setProperty("value", 0)
        self.cuelloVerticalSlider.setSliderPosition(0)
        self.cuelloVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.cuelloVerticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.cuelloVerticalSlider.setObjectName("cuelloVerticalSlider")
        self.cuelloVerticalLabel = QtWidgets.QLabel(self.centralwidget)
        self.cuelloVerticalLabel.setGeometry(QtCore.QRect(590, 320, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cuelloVerticalLabel.setFont(font)
        self.cuelloVerticalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cuelloVerticalLabel.setObjectName("cuelloVerticalLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cuello_label.setText(_translate("MainWindow", "Cuello"))
        self.cuelloHorizontalLabel.setText(_translate("MainWindow", "0"))
        self.cuelloVerticalLabel.setText(_translate("MainWindow", "0"))
